### ISSUE TITLE
关于卷积层bias 梯度的计算问题

### ISSUE THREAD

**Issue by lzclzclzc12** [heyxhh/nnet-numpy#1]
根据代码，卷积层的bias在前向传播计算过程中广播了batch_size * h_out * w_out 次，而求梯度时直接将batch_size * h_out * w_out次梯度相加。我想问的是 是否应该除以bacth_size呢？
`# 计算前向传播
        out = self.w_row @ self.x_col + self.b  # @在numpy中相当于矩阵乘法，等价于numpy.matmul()`
`# 计算反向传播
d_b = d_out_col.sum(axis=1).reshape(self.n_filter, 1)`

**Comment by heyxhh** [comment]
> 根据代码，卷积层的bias在前向传播计算过程中广播了batch_size * h_out * w_out 次，而求梯度时直接将batch_size * h_out * w_out次梯度相加。我想问的是 是否应该除以bacth_size呢？
> `# 计算前向传播 out = self.w_row @ self.x_col + self.b # @在numpy中相当于矩阵乘法，等价于numpy.matmul()`
> `# 计算反向传播 d_b = d_out_col.sum(axis=1).reshape(self.n_filter, 1)`

是的，我检查了一下代码，在求梯度时，代码中所有模块，包括卷积、全连接层的代码，参数的梯度都没有在batch维度上取平均，只求了原始数据的梯度。可在optim.py中优化梯度时除以个batch size即可。

**Comment by lzclzclzc12** [comment]
> > 根据代码，卷积层的bias在前向传播计算过程中广播了batch_size * h_out * w_out 次，而求梯度时直接将batch_size * h_out * w_out次梯度相加。我想问的是 是否应该除以bacth_size呢？
> > `# 计算前向传播 out = self.w_row @ self.x_col + self.b # @在numpy中相当于矩阵乘法，等价于numpy.matmul()`
> > `# 计算反向传播 d_b = d_out_col.sum(axis=1).reshape(self.n_filter, 1)`
> 
> 是的，我检查了一下代码，在求梯度时，代码中所有模块，包括卷积、全连接层的代码，参数的梯度都没有在batch维度上取平均，只求了原始数据的梯度。可在optim.py中优化梯度时除以个batch size即可。

好的，谢谢

**Comment by heyxhh** [comment]
在卷积网络求梯度时没有把梯度除以batch size。我的代码在lossfunctions.py中设计损失函数时，将得到的损失除以了batch size。你也可以修改为在求optim时在batch维度求梯度的平均。
